### PR TITLE
Fix `manifest.json` to comply with current requirements.

### PR DESCRIPTION
**Pull request by sdwilsh**
Sorts and updates `manifest.json` to bring it up to [spec](https://developers.home-assistant.io/docs/creating_integration_manifest/).  There have been changes to the `manifest.json` file since this integration was created.

I have not tested this, but this probably addresses what is raised in #3.

### CODE REVIEW

**Comment by sdwilsh** [comment]
This will certainly fix the hassfest issues that stopped the cron job from running.

**Comment by dcramer** [comment]
Thanks! Meant to f/u here and it got lost in my inbox.

I have noticed mixed results on this working lately, but have been so busy with summer I haven't had a chance to debug.

**Comment by dcramer** [comment]
Looks like the hacs validation is failing - possible thats out of date/wrong though?

**Comment by sdwilsh** [comment]
I'll play around with this tonight and get it passing.

The days are getting shorter, and I want to get my lights a bit more
automated :)

**Comment by sdwilsh** [comment]
I'll address the unit tests in a different PR later, but this should address the issue that the linter was getting hung up on.

**Comment by sdwilsh** [comment]
hassfest is now passing :)

If it's alright with you, I'd like to get this merged, and then I'll fix up tests in a new PR. I should be able to work on that tonight.  The plus side is that I shouldn't need to have my CI runs approved once this is merged because I won't be a first time contributor.

**Comment by dcramer** [comment]
@sdwilsh yeah thats fine - i wont be able to test on my system til late this month anyways

**Pull request merged**
