### PR TITLE
Fix device entities and update version

### PR DESCRIPTION
**Pull request by dronenb**

### CODE REVIEW

**Comment by dronenb** [comment]
Fix #6

**Comment by tfasz** [comment]
Interested in trying this out - any update on if this will be merged?

**Comment by briancmpbll** [comment]
I pulled these changes into my HASS instance and I now get devices for each group and scene on the luxor. They don't seem to update consistently when the groups are turned on outside of home assistant though.

**Comment by dcramer** [comment]
Thanks for the ping! Not sure why I lost this. Do we know if there are differing versions of th Luxor controllers and/or firmware that might be related at all? We're doing some construction so I can't actually test anything, but I have also noticed extremely flakey behavior (on top of some changes to HASS tha thave broken the integration). I will say the flakey behavior has always _somewhat_ been present, and I think is just a property of how the Luxor controllers work.

**Comment by dcramer** [comment]
Also, I'm going to go ahead and merge this given @briancmpbll has at least verified its not completely broken, but if folks report breakage we can consider some kind of version branding and support both paths.

**Pull request merged**
